# -*- coding: utf-8 -*-
"""analisis_rwh_aceh_barat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfutUJRFEGDfFwXsRnetYlJD1wZxUDzU
"""

!pip install geopandas folium pandas openpyxl matplotlib

import geopandas as gpd
import pandas as pd
import folium

# 1. BACA DATA SPASIAL
import os
import zipfile

# Helper function to find a .shp file recursively
def find_shp_file(directory, target_name):
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.shp') and target_name in file:
                return os.path.join(root, file)
    return None

# Define the paths for the zip files and their unzipped directories
pemukiman_zip_path = '/content/pemukiman.zip'
kecamatan_zip_path = '/content/kecamatan.zip'

pemukiman_unzip_dir = '/content/pemukiman_unzipped'
kecamatan_unzip_dir = '/content/kecamatan_unzipped'

# Create directories if they don't exist
os.makedirs(pemukiman_unzip_dir, exist_ok=True)
os.makedirs(kecamatan_unzip_dir, exist_ok=True)

# Unzip pemukiman.zip
with zipfile.ZipFile(pemukiman_zip_path, 'r') as zip_ref:
    zip_ref.extractall(pemukiman_unzip_dir)
print(f"Unzipped {pemukiman_zip_path} to {pemukiman_unzip_dir}/")

# Unzip kecamatan.zip
with zipfile.ZipFile(kecamatan_zip_path, 'r') as zip_ref:
    zip_ref.extractall(kecamatan_unzip_dir)
print(f"Unzipped {kecamatan_zip_path} to {kecamatan_unzip_dir}/")

# Find the actual .shp file paths
pemukiman_shp_path = find_shp_file(pemukiman_unzip_dir, 'PEMUKIMAN_AR_50K')
kecamatan_shp_path = find_shp_file(kecamatan_unzip_dir, 'ADMINISTRASIKECAMATAN_AR_50K')

if not pemukiman_shp_path or not kecamatan_shp_path:
    raise FileNotFoundError("Could not find one or more .shp files after unzipping. Please check the filenames and zip contents.")

peta_pemukiman = gpd.read_file(pemukiman_shp_path)
peta_kecamatan = gpd.read_file(kecamatan_shp_path)
peta_pemukiman = peta_pemukiman.to_crs(epsg=4326)
peta_kecamatan = peta_kecamatan.to_crs(epsg=4326)

# 2. BACA DATA HUJAN
data_hujan = pd.read_excel('DATA HUJAN ACEH BARAT R.xlsx', skiprows=10, header=None)
CH_tahunan_m = (data_hujan[3].sum() / len(data_hujan[0].unique())) / 1000

# 3. KALKULASI POTENSI RWH
peta_pemukiman['Luas_m2'] = peta_pemukiman.geometry.area
peta_pemukiman['Potensi_RWH_m3'] = peta_pemukiman['Luas_m2'] * 0.8 * CH_tahunan_m

# 4. GABUNG DATA PENDUDUK KE KECAMATAN
df_penduduk = pd.read_csv('data_penduduk.csv')

# Check and print columns for debugging
print(f"Columns in peta_kecamatan: {peta_kecamatan.columns.tolist()}")
print(f"Columns in df_penduduk: {df_penduduk.columns.tolist()}")

# Using 'NAMOBJ' from peta_kecamatan to match 'Kecamatan' from df_penduduk
peta_kecamatan = peta_kecamatan.merge(df_penduduk, left_on='NAMOBJ', right_on='Kecamatan')

print("Data berhasil diolah dan digabung!")

import folium

# 1. Inisialisasi peta di koordinat Aceh Barat
m = folium.Map(location=[4.1333, 96.1333], zoom_start=11, tiles="CartoDB positron")

# 2. Tambahkan Layer Batas Kecamatan (Garis Hitam)
folium.GeoJson(
    peta_kecamatan,
    name="Batas Kecamatan",
    style_function=lambda x: {'color': 'black', 'weight': 2, 'fillOpacity': 0}
).add_to(m)

# 3. Tambahkan Layer Pemukiman (Warna Gradasi Potensi RWH)
# Kita pakai choropleth agar warnanya mewakili angka potensi

# Create a copy and add a new column 'id_for_choropleth' from the GeoDataFrame's index
peta_pemukiman_for_choropleth = peta_pemukiman.copy()
peta_pemukiman_for_choropleth['id_for_choropleth'] = peta_pemukiman_for_choropleth.index

folium.Choropleth(
    geo_data=peta_pemukiman_for_choropleth,
    data=peta_pemukiman_for_choropleth,
    columns=['id_for_choropleth', 'Potensi_RWH_m3'], # Use the new column as the identifier
    key_on='feature.id',
    fill_color='YlGnBu',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Potensi Air Hujan (m3)'
).add_to(m)

# 4. Simpan hasil akhir
m.save('index.html')
print("SELESAI! File index.html sudah jadi di panel Files sebelah kiri.")

# Menulis daftar library yang terinstall ke file requirements.txt
!pip freeze > requirements.txt
print("File requirements.txt berhasil dibuat.")

import sys
import platform

# Menulis informasi sistem dan versi Python ke sessioninfo.txt
with open('sessioninfo.txt', 'w') as f:
    f.write(f"Python version: {sys.version}\n")
    f.write(f"Platform: {platform.platform()}\n")
    f.write(f"Library versions:\n")
    f.write("!pip list") # Menampilkan list library saat ini

print("File sessioninfo.txt berhasil dibuat.")